modLoader="javafml" #mandatory

loaderVersion="[28,)" #mandatory (24 is current forge version)

issueTrackerURL="https://github.com/Shadows-of-Fire/Attained-Drops-2/issues" #optional

displayURL="https://minecraft.curseforge.com/projects/attained-drops-2" #optional

license="MIT License" #mandatory

authors="Shadows_of_Fire" #optional

[[mods]] #mandatory

modId="attained_drops" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Attained Drops" #mandatory


description='''
A mod for farming mob drops.
'''

[[dependencies.attained_drops]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33.0.22,)" #mandatory
    ordering="NONE"
    side="BOTH"
	
[[dependencies.attained_drops]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.attained_drops]]
    modId="placebo"
    mandatory=true
    versionRange="[4.2,)"
    ordering="NONE"
    side="BOTH"